### PR TITLE
Changed 1d placefield structure a bit

### PR DESCRIPTION
**Pull request by nkinsky**
Main change is to retain different run direction analyses for 1d placefields in separate dictionaries so that you don't have to re-run .compute() each time you want to plot.  

Also a few small bugfixes and formatting changes.

### CODE REVIEW

**Comment by bapungiri** [comment]
### Questions
So with the previous api, I can do the following:
```python
sess.placefield.pf1d.compute(track_name='maze', run_dir='forward')
sess.placefield.pf1d.phase_precession()
sess.placefield.pf1d.plot()
sess.placefield.pf1d.plot_with_phase()
```
But now with this newer one, you have to specify `run_dir` for each line following the `compute`:
 ```python
sess.placefield.pf1d.compute(track_name='maze', run_dir='forward')
sess.placefield.pf1d.phase_precession(run_dir='forward')
sess.placefield.pf1d.plot(run_dir='forward')
sess.placefield.pf1d.plot(run_dir='forward')
```
Now if I want to compute `backward`, you will have to change the keyword argument for all lines. I still like the previous one as ratemaps are calculated in the first step and the following plots are just using what has been computed. That also plays well with `decode.bayes1d`, as it uses the ratemaps calculated in `compute` and I don't need to specify `run_dir` there.

**Comment by nkinsky** [comment]
Gotcha.  Makes sense.  

My impetus for this change: I would like have side-by-side plots of placefields for each direction in the same figure.  This can't happen as previously written.

However, maybe we could have it both ways with the following workflow:

1)  Run the method `sess.placefield.pf1d.compute(track_name="forward", run_dir="forward")' and write `self.run_dir=forward`.

2) adjust the default input to be `run_dif=self.run_dir` in `.phase_precession()`, `.plot()`, and `.plot_w_phase()`, e.g.:
`def phase_precession(self, theta_chan, run_dir=self.run_dir):`

This _should_ allow you to run the workflow without specifying any inputs.

Of course, we would need to adjust any code where this occurs, e.g. in `.decode.bayes1d` and 'decode.decode_events':

```
mapinfo = pf1d_obj.no_thresh[pf1d_obj.run_dir]
if speed_thresh:
    mapinfo = pf1d_obj.thresh[pf1d_obj.run_dir]
```

Thoughts? I will need to implement this somehow, and this solution seems the cleanest to me.

**Comment by bapungiri** [comment]
Sorry, why can't you plot them side by side ?

This code does it
```python
sess.placefield.pf1d.compute(track_name="maze1", run_dir="foward")
ax= plt.subplot(gs[0])
sess.placefield.pf1d.plot(ax=ax, speed_thresh=True, normalize=True)

# if you want to preserve the cell order
ratemaps = sess.placefield.pf1d.no_thresh["ratemaps"]
cell_order = np.argsort(np.argmax(np.asarray(ratemaps), axis=1))

sess.placefield.pf1d.compute(track_name="maze1", run_dir="backward")
ax= plt.subplot(gs[1])
sess.placefield.pf1d.plot(ax=ax, speed_thresh=True, normalize=True, sortby=cell_order)

```

**Comment by nkinsky** [comment]
I had a similar thought right after I hit send on the last comment. I tried to test something out but ran into a PYTHONPATH issue on my windows machine that wouldn't let me import any modules correctly.  Just fixed it.


My end goal is to have a plot with the 1d placefield for each cell along with its phase precession plot and other info pertinent to that cell (e.g. autocorrelogram) all side-by-side in the same plot.  This would entail running '.compute()' in each direction for every cell I plot, so I was concerned it would take forever.


However, it looks like .compute takes almost no time at all to run, so your solution could work. However, I only have 15 cells.  How long does it take you to run on your 100+ cell sessions?


Nat


Nathaniel Kinsky, PhD

Postdoctoral Fellow

Diba Neural Circuits and Memory Lab

nkinsky@umich.edu

________________________________

**Comment by bapungiri** [comment]
Oh I see, didn't know that you were using windows. Yeah, I never tested these in windows environment. Glad you fixed the pythonpath issue.

For me it is almost instant for my sessions.

One question though, why do you need to run it for every cell ? It computes across all cells at once, right ? What i got from your requirement is a plot method that specifically plots a given cell. I previously wanted to implement the same with something like
```python
sess.placefield.pf1d.plot_cell(ax= ax, cell_id = 2, phase = True)

(OR)

#incorporate in existing method
sess.placefield.pf1d.plot(ax=ax, sortby= cell_ids) # plots only cells mentioned in sortby

```

**Comment by nkinsky** [comment]
Ok cool. That's good to hear it's super fast even with a lot of cells.  

Not usually using windows, but my laptop is windows and I do a bit of analysis sometimes in lab so I need it here.

As for computing for each cell, my end goal was to have a widget that would allow me to scroll through each cell, so I would have to run `.compute(run_dir="forward")` then `.plot_cell(ax=ax[0], cell_id=1)` then `.compute(run_dir="backward")` then '.plot_cell(ax=ax[1], cell_id=1)` to display everything for cell 1.  Then I would have to run the same code again for cell 2 and so on, since the data stored in `self.no_thresh' would only be for one direction.  But since it is super fast to compute this doesn't seem to be an issue. However, if could be an issue for phase_precession...

How fast is `.phase_precession` for you? That seems to take a few seconds for each run even on my more powerful desktop.

**Comment by bapungiri** [comment]
Yeah `.phase_precession` will be a little slow because of working with eeg file.

Since everything is an object, you can use the following to avoid doing it for each cell iteratively.
```python
from copy import deepcopy

sess.placefield.pf1d.compute(track_name="maze1", run_dir="foward")
sess.placefield.pf1d.phase_precession()
pf_forward = deepcopy(sess.placefield.pf1d)

sess.placefield.pf1d.compute(track_name="maze1", run_dir="backward")
sess.placefield.pf1d.phase_precession()
pf_backward = deepcopy(sess.placefield.pf1d)

# now you can cycle over only plots not compute
fig,ax = plt.subplots(1,2)
for cell_num in range(10):
  pf_forward.plot_cell(ax=ax[0],cell_id=cell_num)
  pf_backward.plot_cell(ax=ax[1],cell_id=cell_num)

```

**Comment by nkinsky** [comment]
Ok cool! That works.  Would never have figured this out on my own, so much appreciated. Or maybe I would have but I would have been much more complicated.


So I guess then we would reject this pull request? Not actually sure how to do that.


Nat


Nathaniel Kinsky, PhD

Postdoctoral Fellow

Diba Neural Circuits and Memory Lab

nkinsky@umich.edu

________________________________

**Comment by bapungiri** [comment]
Not entirely sure. Looks like we can close this pull request, but you have other commits that we want to accept. I see some `delete file` option for each commit within the pull request, but what that does trying to find out.

**Comment by nkinsky** [comment]
Looks like we can use the `cherry-pick` flag with git from the command line.  I can take care of this later tonight/tomorrow:  https://mattstauffer.com/blog/how-to-merge-only-specific-commits-from-a-pull-request/

**Comment by nkinsky** [comment]
Just a heads up that I tried and failed to use cherry_pick to merge only the selected commits.  So don't pull from here until I fix it!  I accidentally merged in everything!

**Pull request merged**
